// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSse_6ZmZa98GHA_4xta27viR8U_Tmojw',
    appId: '1:94145546051:web:9fe7f0ce4c12b3edc5d1f6',
    messagingSenderId: '94145546051',
    projectId: 'citiguide-32c72',
    authDomain: 'citiguide-32c72.firebaseapp.com',
    storageBucket: 'citiguide-32c72.appspot.com',
    measurementId: 'G-Q84HB4X353',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJm3cKgH38WTkcWL_GUn1GzWpBgPF4oT8',
    appId: '1:94145546051:android:4acbb280eddb1245c5d1f6',
    messagingSenderId: '94145546051',
    projectId: 'citiguide-32c72',
    storageBucket: 'citiguide-32c72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcYPxJECbQFIRwbdWLfmBqPdgKhVLsNQE',
    appId: '1:94145546051:ios:73c40267862fa955c5d1f6',
    messagingSenderId: '94145546051',
    projectId: 'citiguide-32c72',
    storageBucket: 'citiguide-32c72.appspot.com',
    iosBundleId: 'com.example.citiguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcYPxJECbQFIRwbdWLfmBqPdgKhVLsNQE',
    appId: '1:94145546051:ios:73c40267862fa955c5d1f6',
    messagingSenderId: '94145546051',
    projectId: 'citiguide-32c72',
    storageBucket: 'citiguide-32c72.appspot.com',
    iosBundleId: 'com.example.citiguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSse_6ZmZa98GHA_4xta27viR8U_Tmojw',
    appId: '1:94145546051:web:63af093db04eade1c5d1f6',
    messagingSenderId: '94145546051',
    projectId: 'citiguide-32c72',
    authDomain: 'citiguide-32c72.firebaseapp.com',
    storageBucket: 'citiguide-32c72.appspot.com',
    measurementId: 'G-R9NBBY3KNM',
  );
}
